language: perl

os:
    - linux
#    - osx

sudo: true

#fast_finish: true

install: "echo"
before_install:
  - openssl aes-256-cbc -K $encrypted_6f7e9e1784cd_key -iv $encrypted_6f7e9e1784cd_iv -in deploy_key.enc -out deploy_key -d;
  - chmod 600 deploy_key;
  - eval `ssh-agent -s`
  - ssh-add deploy_key
dist: trusty

addons:
  apt:
    packages:
        - libappstream0
        - libappstream-dev
        - gir1.2-appstream
        - appstream-index

script:
    - chmod +x build-appimage.sh
    - ./build-appimage.sh
    - APPIMAGE="$(find . -name '*.AppImage')"
    - echo "Testing launching scripts and using modules" && eval "$APPIMAGE $(pwd)/t/00-exists.t"
    - ./update-gh-pages.sh

on_success:
branches:
   only:
     - /.*/

notifications:
  irc:
    channels:
      - "irc.freenode.net#perl6-dev"
    on_success: never
    on_failure: never
    template:
      - "Rakudo build %{result}. %{author} '%{commit_message}'"
      - "%{build_url} %{compare_url}"

env:
  global:
  matrix:
    - BLEAD=1 P6SCRIPT=testing
    - BLEAD=1 P6SCRIPT=stable
    - STAR=1  P6SCRIPT=stable
    - STAR=1  P6SCRIPT=testing


matrix:
  allow_failures:
    - env: BLEAD=1 P6SCRIPT=testing
    - env: STAR=1  P6SCRIPT=testing
