language: perl

os:
  - linux
# - osx

sudo: true

#fast_finish: true

install: "echo"
before_install:
  # Put github's into known_hosts /* may not need this */
  - printf "github.com,192.30.255.112 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==\n" >> ~/.ssh/known_hosts
  - openssl aes-256-cbc -K $encrypted_6f7e9e1784cd_key -iv $encrypted_6f7e9e1784cd_iv -in deploy_key.enc -out deploy_key -d;
  - chmod 600 deploy_key;
  - eval `ssh-agent -s`
  - expect -c 'spawn ssh-add ./deploy_key; expect "enter passphrase for"; send "\n"; expect "Identity added:"; interact'
#  - ssh-add deploy_key
dist: trusty

addons:
  apt:
    packages:
      # appstream needed for building the appimage
      - libappstream0
      - libappstream-dev
      - gir1.2-appstream
      - appstream-index
      # noninteractive helper
      - expect

script:
  - find_file () { readlink -f  "$(find . -maxdepth 1 -type f -name "$1" | head -n 1)"; }
  - find_dir () { readlink -f  "$(find . -maxdepth 1 -type d -name "$1" | head -n 1)"; }
  - STABLE_TEST="$(find_file 'stable-test.txt')"
  - chmod +x build-appimage.sh
  - ./build-appimage.sh
  - APPIMAGE=$(find_file '*.AppImage')
  - printf 'AppImage is %s\n' "$APPIMAGE"
  - echo "Testing launching scripts and using modules"; eval "$APPIMAGE $(pwd)/t/00-exists.t"
  - eval "$APPIMAGE --help"
  - eval "$APPIMAGE --version"
  # Copy the appimage to perl6-m so we can do testing
  # not sure why it was failing to copy...
  - RAKUDO_DIR=$(find_dir 'rakudo*')
  - sudo cp -v "$APPIMAGE" "$RAKUDO_DIR/perl6-m"
  - pwd
  - ls -lh
  - echo "Rakudo dir is $RAKUDO_DIR"
  - cd "$RAKUDO_DIR"
  - ls -lh
  - if [ "$STAR" ]; then cd rakudo; fi
  #- pwd
#  - ls -lh
  # Tests that should pass
  - perl t/harness5 --verbosity=5 $(cat $STABLE_TEST )
  # Tests that may pass or may not pass
  - echo "Following tests are the full test suite but are not part of travis return"
  - /usr/bin/perl t/harness5 --verbosity=5 t/01-sanity t/04-nativecall || echo "Ignoring return value for Travis"

after_success:
  - cd "$TRAVIS_BUILD_DIR"
  - echo "Running on success options"
  - ./update-gh-pages.sh
branches:
  only:
    - /.*/

notifications:
  irc:
    channels:
      - "irc.freenode.net#perl6-dev"
    on_success: never
    on_failure: never
    template:
      - "Rakudo build %{result}. %{author} '%{commit_message}'"
      - "%{build_url} %{compare_url}"

env:
  global:
  matrix:
    - BLEAD=1 P6SCRIPT=testing
    - BLEAD=1 P6SCRIPT=stable
    - STAR=1  P6SCRIPT=stable
    - STAR=1  P6SCRIPT=testing


matrix:
  allow_failures:
    - env: BLEAD=1 P6SCRIPT=testing
    - env: STAR=1  P6SCRIPT=testing
